export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const UPDATE_LOGO_ADS_REQUEST = "UPDATE_LOGO_ADS_REQUEST";
export const UPDATE_LOGO_ADS_SUCCESS = "UPDATE_LOGO_ADS_SUCCESS";
export const UPDATE_LOGO_ADS_FAIL = "UPDATE_LOGO_ADS_FAIL";

export const GET_LOGO_ADS_REQUEST = "GET_LOGO_ADS_REQUEST";
export const GET_LOGO_ADS_SUCCESS = "GET_LOGO_ADS_SUCCESS";
export const GET_LOGO_ADS_FAIL = "GET_LOGO_ADS_FAIL";
