export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL';

export const ADMIN_CREATE_CATEGORY_REQUEST = 'ADMIN_CREATE_CATEGORY_REQUEST';
export const ADMIN_CREATE_CATEGORY_SUCCESS = 'ADMIN_CREATE_CATEGORY_SUCCESS';
export const ADMIN_CREATE_CATEGORY_FAIL = 'ADMIN_CREATE_CATEGORY_FAIL';

export const ADMIN_GET_CATEGORY_BY_ID_REQUEST =
  'ADMIN_GET_CATEGORY_BY_ID_REQUEST';
export const ADMIN_GET_CATEGORY_BY_ID_SUCCESS =
  'ADMIN_GET_CATEGORY_BY_ID_SUCCESS';
export const ADMIN_GET_CATEGORY_BY_ID_FAIL = 'ADMIN_GET_CATEGORY_BY_ID_FAIL';

export const ADMIN_DELETE_CATEGORY_BY_ID_REQUEST =
  'ADMIN_DELETE_CATEGORY_BY_ID_REQUEST';
export const ADMIN_DELETE_CATEGORY_BY_ID_SUCCESS =
  'ADMIN_DELETE_CATEGORY_BY_ID_SUCCESS';
export const ADMIN_DELETE_CATEGORY_BY_ID_FAIL =
  'ADMIN_DELETE_CATEGORY_BY_ID_FAIL';

export const ADMIN_UPDATE_CATEGORY_REQUEST = 'ADMIN_UPDATE_CATEGORY_REQUEST';
export const ADMIN_UPDATE_CATEGORY_SUCCESS = 'ADMIN_UPDATE_CATEGORY_SUCCESS';
export const ADMIN_UPDATE_CATEGORY_FAIL = 'ADMIN_UPDATE_CATEGORY_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
