export const SELECTED_CURRENCY = 'SELECTED_CURRENCY';

export const CURR_REQUEST = 'CURR_REQUEST';
export const CURR_SUCCESS = 'CURR_SUCCESS';
export const CURR_FAIL = 'CURR_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
