export const USER_ADD_ORDER_REQUEST = "USER_ADD_ORDER_REQUEST";
export const USER_ADD_ORDER_SUCCESS = "USER_ADD_ORDER_SUCCESS";
export const USER_ADD_ORDER_FAIL = "USER_ADD_ORDER_FAIL";

export const GET_USER_ORDER_REQUEST = "GET_USER_ORDER_REQUEST";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAIL = "GET_USER_ORDER_FAIL";

//*Stay
export const GET_SELLER_INFO_REQUEST = "GET_SELLER_INFO_REQUEST";
export const GET_SELLER_INFO_SUCCESS = "GET_SELLER_INFO_SUCCESS";
export const GET_SELLER_INFO_FAIL = "GET_SELLER_INFO_FAIL";

export const GET_SELLER_ORDERS_REQUEST = "GET_SELLER_ORDERS_REQUEST";
export const GET_SELLER_ORDERS_SUCCESS = "GET_SELLER_ORDERS_SUCCESS";
export const GET_SELLER_ORDERS_FAIL = "GET_SELLER_ORDERS_FAIL";

export const GET_SINGLE_ORDER_REQUEST = "GET_SINGLE_ORDER_REQUEST";
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS";
export const GET_SINGLE_ORDER_FAIL = "GET_SINGLE_ORDER_FAIL";

export const UPDATE_SINGLE_ORDER_REQUEST = "UPDATE_SINGLE_ORDER_REQUEST";
export const UPDATE_SINGLE_ORDER_SUCCESS = "UPDATE_SINGLE_ORDER_SUCCESS";
export const UPDATE_SINGLE_ORDER_FAIL = "UPDATE_SINGLE_ORDER_FAIL";

export const UPDATE_SHOP_INFO_REQUEST = "UPDATE_SHOP_INFO_REQUEST";
export const UPDATE_SHOP_INFO_SUCCESS = "UPDATE_SHOP_INFO_SUCCESS";
export const UPDATE_SHOP_INFO_FAIL = "UPDATE_SHOP_INFO_FAIL";

export const ADMIN_GET_ORDERS_REQUEST = "ADMIN_GET_ORDERS_REQUEST";
export const ADMIN_GET_ORDERS_SUCCESS = "ADMIN_GET_ORDERS_SUCCESS";
export const ADMIN_GET_ORDERS_FAIL = "ADMIN_GET_ORDERS_FAIL";

export const ADMIN_GET_ORDER_DET_REQUEST = "ADMIN_GET_ORDER_DET_REQUEST";
export const ADMIN_GET_ORDER_DET_SUCCESS = "ADMIN_GET_ORDER_DET_SUCCESS";
export const ADMIN_GET_ORDER_DET_FAIL = "ADMIN_GET_ORDER_DET_FAIL";

export const ADMIN_UPDATE_STATUS_REQUEST = "ADMIN_UPDATE_STATUS_REQUEST";
export const ADMIN_UPDATE_STATUS_SUCCESS = "ADMIN_UPDATE_STATUS_SUCCESS";
export const ADMIN_UPDATE_STATUS_FAIL = "ADMIN_UPDATE_STATUS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
