// export const ADD_ITEM_TO_CART_REQUEST = 'ADD_ITEM_TO_CART_REQUEST';
// export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
// export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';
export const DECREASE_QTY = 'DECREASE_QTY';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const RESET_CART = 'RESET_CART';

export const GET_CART_ITEMS_DB_REQUEST = 'GET_CART_ITEMS_DB_REQUEST';
export const GET_CART_ITEMS_DB_SUCCESS = 'GET_CART_ITEMS_DB_SUCCESS';
export const GET_CART_ITEMS_DB_FAIL = 'GET_CART_ITEMS_DB_FAIL';
export const GET_CART_ITEMS_LOCAL = 'GET_CART_ITEMS_LOCAL';

export const REMOVE_ITEM_DB_REQUEST = 'REMOVE_ITEM_DB_REQUEST';
export const REMOVE_ITEM_DB_SUCCESS = 'REMOVE_ITEM_DB_SUCCESS';
export const REMOVE_ITEM_DB_FAIL = 'REMOVE_ITEM_DB_FAIL';

export const DECREASE_QTY_DB_REQUEST = 'DECREASE_QTY_DB_REQUEST';
export const DECREASE_QTY_DB = 'DECREASE_QTY_DB';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
