// export const ADD_ITEM_TO_CART_REQUEST = 'ADD_ITEM_TO_CART_REQUEST';
// export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
// export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';
export const DECREASE_QTY = 'DECREASE_QTY';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const RESET_CART = 'RESET_CART';
