export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ADMIN_CREATE_CATEGORY_REQUEST = 'ADMIN_CREATE_CATEGORY_REQUEST';
export const ADMIN_CREATE_CATEGORY_SUCCESS = 'ADMIN_CREATE_CATEGORY_SUCCESS';
export const ADMIN_CREATE_CATEGORY_FAIL = 'ADMIN_CREATE_CATEGORY_FAIL';
