export const USER_ADD_ORDER_REQUEST = 'USER_ADD_ORDER_REQUEST';
export const USER_ADD_ORDER_SUCCESS = 'USER_ADD_ORDER_SUCCESS';
export const USER_ADD_ORDER_FAIL = 'USER_ADD_ORDER_FAIL';

export const GET_USER_ORDER_REQUEST = 'GET_USER_ORDER_REQUEST';
export const GET_USER_ORDER_SUCCESS = 'GET_USER_ORDER_SUCCESS';
export const GET_USER_ORDER_FAIL = 'GET_USER_ORDER_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
