export const ADMIN_CREATE_PRODUCT_REQUEST = 'ADMIN_CREATE_PRODUCT_REQUEST';
export const ADMIN_CREATE_PRODUCT_SUCCESS = 'ADMIN_CREATE_PRODUCT_SUCCESS';
export const ADMIN_CREATE_PRODUCT_FAIL = 'ADMIN_CREATE_PRODUCT_FAIL';

export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAIL = 'ADMIN_DELETE_PRODUCT_FAIL';

export const ADMIN_UPDATE_PRODUCT_REQUEST = 'ADMIN_UPDATE_PRODUCT_REQUEST';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAIL = 'ADMIN_UPDATE_PRODUCT_FAIL';

export const ADMIN_GET_ALL_PRODUCTS_REQUEST = 'ADMIN_GET_ALL_PRODUCTS_REQUEST';
export const ADMIN_GET_ALL_PRODUCTS_SUCCESS = 'ADMIN_GET_ALL_PRODUCTS_SUCCESS';
export const ADMIN_GET_ALL_PRODUCTS_FAIL = 'ADMIN_GET_ALL_PRODUCTS_FAIL';

export const GET_PRODUCTS_BY_SLUG_REQUEST = 'GET_PRODUCTS_BY_SLUG_REQUEST';
export const GET_PRODUCTS_BY_SLUG_SUCCESS = 'GET_PRODUCTS_BY_SLUG_SUCCESS';
export const GET_PRODUCTS_BY_SLUG_FAIL = 'GET_PRODUCTS_BY_SLUG_FAIL';

//!CUS means customers
export const GET_CUS_PRODUCTS_REQUEST = 'GET_CUS_PRODUCTS_REQUEST';
export const GET_CUS_PRODUCTS_SUCCESS = 'GET_CUS_PRODUCTS_SUCCESS';
export const GET_CUS_PRODUCTS_FAIL = 'GET_CUS_PRODUCTS_FAIL';

export const GET_CUS_PRODUCT_BY_ID_REQUEST = 'GET_CUS_PRODUCT_BY_ID_REQUEST';
export const GET_CUS_PRODUCT_BY_ID_SUCCESS = 'GET_CUS_PRODUCT_BY_ID_SUCCESS';
export const GET_CUS_PRODUCT_BY_ID_FAIL = 'GET_CUS_PRODUCT_BY_ID_FAIL';

export const GET_SHOP_PRODUCT_REQUEST = 'GET_SHOP_PRODUCT_REQUEST';
export const GET_SHOP_PRODUCT_SUCCESS = 'GET_SHOP_PRODUCT_SUCCESS';
export const GET_SHOP_PRODUCT_FAIL = 'GET_SHOP_PRODUCT_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
