export const ADMIN_CREATE_PRODUCT_REQUEST = 'ADMIN_CREATE_PRODUCT_REQUEST';
export const ADMIN_CREATE_PRODUCT_SUCCESS = 'ADMIN_CREATE_PRODUCT_SUCCESS';
export const ADMIN_CREATE_PRODUCT_FAIL = 'ADMIN_CREATE_PRODUCT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
