export const ADMIN_CREATE_PRODUCT_REQUEST = 'ADMIN_CREATE_PRODUCT_REQUEST';
export const ADMIN_CREATE_PRODUCT_SUCCESS = 'ADMIN_CREATE_PRODUCT_SUCCESS';
export const ADMIN_CREATE_PRODUCT_FAIL = 'ADMIN_CREATE_PRODUCT_FAIL';

export const GET_PRODUCTS_BY_SLUG_REQUEST = 'GET_PRODUCTS_BY_SLUG_REQUEST';
export const GET_PRODUCTS_BY_SLUG_SUCCESS = 'GET_PRODUCTS_BY_SLUG_SUCCESS';
export const GET_PRODUCTS_BY_SLUG_FAIL = 'GET_PRODUCTS_BY_SLUG_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
