export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const GOOGLE_SIGN_REQUEST = 'GOOGLE_SIGN_REQUEST';
export const GOOGLE_SIGN_SUCCESS = 'GOOGLE_SIGN_SUCCESS';
export const GOOGLE_SIGN_FAIL = 'GOOGLE_SIGN_FAIL';

export const FACEBOOK_SIGN_REQUEST = 'FACEBOOK_SIGN_REQUEST';
export const FACEBOOK_SIGN_SUCCESS = 'FACEBOOK_SIGN_SUCCESS';
export const FACEBOOK_SIGN_FAIL = 'FACEBOOK_SIGN_FAIL';

export const LOAD_PROFILE_REQUEST = 'LOAD_PROFILE_REQUEST';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_TOKEN_FROM_COOKIE = 'GET_TOKEN_FROM_COOKIE';

export const LOGOUT = 'LOGOUT';

export const GET_USER_ADDRESS_REQUEST = 'GET_USER_ADDRESS_REQUEST';
export const GET_USER_ADDRESS_SUCCESS = 'GET_USER_ADDRESS_SUCCESS';
export const GET_USER_ADDRESS_FAIL = 'GET_USER_ADDRESS_FAIL';

export const ADD_USER_ADDRESS_REQUEST = 'ADD_USER_ADDRESS_REQUEST';
export const ADD_USER_ADDRESS_SUCCESS = 'ADD_USER_ADDRESS_SUCCESS';
export const ADD_USER_ADDRESS_FAIL = 'ADD_USER_ADDRESS_FAIL';

export const DELETE_USER_ADDRESS_REQUEST = 'DELETE_USER_ADDRESS_REQUEST';
export const DELETE_USER_ADDRESS_SUCCESS = 'DELETE_USER_ADDRESS_SUCCESS';
export const DELETE_USER_ADDRESS_FAIL = 'DELETE_USER_ADDRESS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
